name: Deploy to Supabase

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: production

        env:
            SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
            SUPABASE_PROJECT_ID: dblnkwjeybdvjxohxpzo

        steps:
            - uses: actions/checkout@v4

            - uses: supabase/setup-cli@v1
              with:
                  version: latest

            - run: cd supabase
            - run: supabase link --project-ref $SUPABASE_PROJECT_ID
            - run: supabase db push
            - run: supabase functions deploy --project-ref $SUPABASE_PROJECT_ID
